### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by sf1234** [ddellamico/ionic2-taxi-app#1]
while installing using 'npm install'. i am using windows machine. 
I encounter the following error:

npm ERR! Failed at the ionic2-taxi-app@0.0.1 postinstall script 'ionic state restore && typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic2-taxi-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic state restore && typings install

please advise

**Comment by sf1234** [comment]
I am able run the following commands successfully:
1- ionic state restore 
2- typings install

but when i run "npm run dev". it does  not initiate the webpack-dev-server. it actually  stops after the following response

> to be executed: "webpack-dev-server"
> process.env.NODE_ENV ====>  development
> platform ====>  android
> theme path ====>  C:\playground\ionic2-taxi-app\ionic2-taxi-app\app\theme\app.md.scss

Please advise.

**Comment by ddellamico** [comment]
Hi sf1234 ! I've just updated this repo with latest ionic version.
Can you try again now ?
Please, open another issue if you get others problems.

Damien
