### ISSUE TITLE
Google Cordova Plugin

### ISSUE THREAD

**Issue by jayeshanandani** [ddellamico/ionic2-taxi-app#4]
Why not use cordova google map plugin? Has JS/TS package of google got any advantage over using cordova google maps plugin?

**Comment by ddellamico** [comment]
Hello @jayeshanandani !

I tried some time ago the cordova map plugin, but I remember I got several issues with that ...
Of course, It's would be nice try again the plugin now, I think a lot of bugs was fixed since I tried it.
